/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.Empleado;
import Clases.Reportes;
import Clases.Usuario;
import Clases.Validaciones;
import Controlador.ControladorEmpleado;
import Controlador.ControladorUsuario;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;



/**
 *
 * @author 
 */
public class Gui_login extends javax.swing.JFrame {

    //Atributos
    public String usuario="";
    public String cargoUsuario="";

    //Constructor
    public Gui_login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    
    /**************************************************/
    //Metodo que se encarga de hacer el logueo de un usuario
    //  String String -> loguear -> String
    public String loguear(String usuario, String password){
        String validacion = null;
        

        if( usuario.trim().isEmpty() || password.trim().isEmpty() ) {
        
            validacion= "Ingrese los datos completos";
        
        }
  
        else{
                        
            Usuario user = new ControladorUsuario().consultarUsuarioPorNombre(usuario);

            if (user.getPassword().equalsIgnoreCase(password)) {

                Empleado empleado = new ControladorEmpleado().consultarEmpleado(user.getIdentificacion());
                String cargo = empleado.getCargo();
                
                this.usuario = empleado.getIdentificacion();
                this.cargoUsuario = cargo;
                System.err.println(cargo);
     
                
                validacion= "Ingreso exitosamente";
                this.dispose();
                 
                      
            }else{
                validacion= "Contraseña incorrecta";
                
            }
        }
        
        jTextFieldIdentificacion.setText("");
        jPassword.setText("");
        return validacion;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelLogin = new javax.swing.JLabel();
        jLabelIncon = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        jTextFieldIdentificacion = new javax.swing.JTextField();
        jButtonIngresar = new javax.swing.JButton();
        jPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabelLogin.setFont(new java.awt.Font("Bodoni MT Black", 1, 36)); // NOI18N
        jLabelLogin.setForeground(new java.awt.Color(102, 102, 102));
        jLabelLogin.setText("LOGIN");
        jPanel1.add(jLabelLogin);
        jLabelLogin.setBounds(10, 20, 150, 30);
        jPanel1.add(jLabelIncon);
        jLabelIncon.setBounds(370, 0, 170, 170);

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelUsuario.setText("Usuario");
        jPanel1.add(jLabelUsuario);
        jLabelUsuario.setBounds(20, 120, 100, 40);

        jLabelContraseña.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelContraseña.setText("Contraseña");
        jPanel1.add(jLabelContraseña);
        jLabelContraseña.setBounds(20, 180, 100, 30);

        jTextFieldIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdentificacionActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldIdentificacion);
        jTextFieldIdentificacion.setBounds(120, 122, 180, 30);

        jButtonIngresar.setBackground(new java.awt.Color(102, 255, 204));
        jButtonIngresar.setText("Ingresar\n");
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonIngresar);
        jButtonIngresar.setBounds(280, 230, 90, 23);

        jPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordKeyPressed(evt);
            }
        });
        jPanel1.add(jPassword);
        jPassword.setBounds(120, 180, 180, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 540, 270);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdentificacionActionPerformed
        // TODO add your handling code here:
       
       
    }//GEN-LAST:event_jTextFieldIdentificacionActionPerformed

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed
        String usuario=jTextFieldIdentificacion.getText();
        String password = jPassword.getText();
        try{
            String validacion = this.loguear(usuario, password);
            if (validacion.equalsIgnoreCase("Ingrese los datos completos")) {
                JOptionPane.showMessageDialog(null, validacion, "Error!", JOptionPane.ERROR_MESSAGE);
            }else if (validacion.equalsIgnoreCase("Contraseña incorrecta")) {
                JOptionPane.showMessageDialog(null, validacion, "Error!", JOptionPane.ERROR_MESSAGE);
            }else if (validacion.equalsIgnoreCase("Ingreso exitosamente")) {
                Gui_VentanaPrincipalGerente principalGenrente = new Gui_VentanaPrincipalGerente(this);
                principalGenrente.setVisible(true);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error al ingresar", "Error!", JOptionPane.ERROR_MESSAGE);
            jPassword.setText("");
            jTextFieldIdentificacion.setText("");
        }
        
        
            
        
        
      
    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void jPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String usuario=jTextFieldIdentificacion.getText();
        String password = jPassword.getText();
        try{
            String validacion = this.loguear(usuario, password);
            if (validacion.equalsIgnoreCase("Ingrese los datos completos")) {
                JOptionPane.showMessageDialog(null, validacion, "Error!", JOptionPane.ERROR_MESSAGE);
            }else if (validacion.equalsIgnoreCase("Contraseña incorrecta")) {
                JOptionPane.showMessageDialog(null, validacion, "Error!", JOptionPane.ERROR_MESSAGE);
            }else if (validacion.equalsIgnoreCase("Ingreso exitosamente")) {
                Gui_VentanaPrincipalGerente principalGenrente = new Gui_VentanaPrincipalGerente(this);
                principalGenrente.setVisible(true);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error al ingresar", "Error!", JOptionPane.ERROR_MESSAGE);
            jPassword.setText("");
            jTextFieldIdentificacion.setText("");
        }
        }
    }//GEN-LAST:event_jPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelIncon;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTextFieldIdentificacion;
    // End of variables declaration//GEN-END:variables
}
